/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5204a0b50cc5c41f5e3f3d5c088cb583)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    MERCHANT_ADDRESS: string
    MERCHANT_PRIVATE_KEY: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'MERCHANT_ADDRESS' | 'MERCHANT_PRIVATE_KEY'>
    > {}
}
