/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DialogIndexRouteImport } from './routes/dialog/index'
import { Route as DialogWallet_sendCallsRouteImport } from './routes/dialog/wallet_sendCalls'
import { Route as DialogWallet_revokePermissionsRouteImport } from './routes/dialog/wallet_revokePermissions'
import { Route as DialogWallet_revokeAdminRouteImport } from './routes/dialog/wallet_revokeAdmin'
import { Route as DialogWallet_prepareUpgradeAccountRouteImport } from './routes/dialog/wallet_prepareUpgradeAccount'
import { Route as DialogWallet_grantPermissionsRouteImport } from './routes/dialog/wallet_grantPermissions'
import { Route as DialogWallet_grantAdminRouteImport } from './routes/dialog/wallet_grantAdmin'
import { Route as DialogWallet_connectRouteImport } from './routes/dialog/wallet_connect'
import { Route as DialogWallet_addFundsRouteImport } from './routes/dialog/wallet_addFunds'
import { Route as DialogSuccessRouteImport } from './routes/dialog/success'
import { Route as DialogPlaygroundRouteImport } from './routes/dialog/playground'
import { Route as DialogPersonal_signRouteImport } from './routes/dialog/personal_sign'
import { Route as DialogPendingRouteImport } from './routes/dialog/pending'
import { Route as DialogEth_signTypedData_v4RouteImport } from './routes/dialog/eth_signTypedData_v4'
import { Route as DialogEth_sendTransactionRouteImport } from './routes/dialog/eth_sendTransaction'
import { Route as DialogEth_requestAccountsRouteImport } from './routes/dialog/eth_requestAccounts'
import { Route as DialogAccount_verifyEmailRouteImport } from './routes/dialog/account_verifyEmail'
import { Route as DialogSplatRouteImport } from './routes/dialog/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogIndexRoute = DialogIndexRouteImport.update({
  id: '/dialog/',
  path: '/dialog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogWallet_sendCallsRoute = DialogWallet_sendCallsRouteImport.update({
  id: '/dialog/wallet_sendCalls',
  path: '/dialog/wallet_sendCalls',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogWallet_revokePermissionsRoute =
  DialogWallet_revokePermissionsRouteImport.update({
    id: '/dialog/wallet_revokePermissions',
    path: '/dialog/wallet_revokePermissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogWallet_revokeAdminRoute =
  DialogWallet_revokeAdminRouteImport.update({
    id: '/dialog/wallet_revokeAdmin',
    path: '/dialog/wallet_revokeAdmin',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogWallet_prepareUpgradeAccountRoute =
  DialogWallet_prepareUpgradeAccountRouteImport.update({
    id: '/dialog/wallet_prepareUpgradeAccount',
    path: '/dialog/wallet_prepareUpgradeAccount',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogWallet_grantPermissionsRoute =
  DialogWallet_grantPermissionsRouteImport.update({
    id: '/dialog/wallet_grantPermissions',
    path: '/dialog/wallet_grantPermissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogWallet_grantAdminRoute = DialogWallet_grantAdminRouteImport.update({
  id: '/dialog/wallet_grantAdmin',
  path: '/dialog/wallet_grantAdmin',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogWallet_connectRoute = DialogWallet_connectRouteImport.update({
  id: '/dialog/wallet_connect',
  path: '/dialog/wallet_connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogWallet_addFundsRoute = DialogWallet_addFundsRouteImport.update({
  id: '/dialog/wallet_addFunds',
  path: '/dialog/wallet_addFunds',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogSuccessRoute = DialogSuccessRouteImport.update({
  id: '/dialog/success',
  path: '/dialog/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogPlaygroundRoute = DialogPlaygroundRouteImport.update({
  id: '/dialog/playground',
  path: '/dialog/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogPersonal_signRoute = DialogPersonal_signRouteImport.update({
  id: '/dialog/personal_sign',
  path: '/dialog/personal_sign',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogPendingRoute = DialogPendingRouteImport.update({
  id: '/dialog/pending',
  path: '/dialog/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogEth_signTypedData_v4Route =
  DialogEth_signTypedData_v4RouteImport.update({
    id: '/dialog/eth_signTypedData_v4',
    path: '/dialog/eth_signTypedData_v4',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogEth_sendTransactionRoute =
  DialogEth_sendTransactionRouteImport.update({
    id: '/dialog/eth_sendTransaction',
    path: '/dialog/eth_sendTransaction',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogEth_requestAccountsRoute =
  DialogEth_requestAccountsRouteImport.update({
    id: '/dialog/eth_requestAccounts',
    path: '/dialog/eth_requestAccounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogAccount_verifyEmailRoute =
  DialogAccount_verifyEmailRouteImport.update({
    id: '/dialog/account_verifyEmail',
    path: '/dialog/account_verifyEmail',
    getParentRoute: () => rootRouteImport,
  } as any)
const DialogSplatRoute = DialogSplatRouteImport.update({
  id: '/dialog/$',
  path: '/dialog/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dialog/$': typeof DialogSplatRoute
  '/dialog/account_verifyEmail': typeof DialogAccount_verifyEmailRoute
  '/dialog/eth_requestAccounts': typeof DialogEth_requestAccountsRoute
  '/dialog/eth_sendTransaction': typeof DialogEth_sendTransactionRoute
  '/dialog/eth_signTypedData_v4': typeof DialogEth_signTypedData_v4Route
  '/dialog/pending': typeof DialogPendingRoute
  '/dialog/personal_sign': typeof DialogPersonal_signRoute
  '/dialog/playground': typeof DialogPlaygroundRoute
  '/dialog/success': typeof DialogSuccessRoute
  '/dialog/wallet_addFunds': typeof DialogWallet_addFundsRoute
  '/dialog/wallet_connect': typeof DialogWallet_connectRoute
  '/dialog/wallet_grantAdmin': typeof DialogWallet_grantAdminRoute
  '/dialog/wallet_grantPermissions': typeof DialogWallet_grantPermissionsRoute
  '/dialog/wallet_prepareUpgradeAccount': typeof DialogWallet_prepareUpgradeAccountRoute
  '/dialog/wallet_revokeAdmin': typeof DialogWallet_revokeAdminRoute
  '/dialog/wallet_revokePermissions': typeof DialogWallet_revokePermissionsRoute
  '/dialog/wallet_sendCalls': typeof DialogWallet_sendCallsRoute
  '/dialog/': typeof DialogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dialog/$': typeof DialogSplatRoute
  '/dialog/account_verifyEmail': typeof DialogAccount_verifyEmailRoute
  '/dialog/eth_requestAccounts': typeof DialogEth_requestAccountsRoute
  '/dialog/eth_sendTransaction': typeof DialogEth_sendTransactionRoute
  '/dialog/eth_signTypedData_v4': typeof DialogEth_signTypedData_v4Route
  '/dialog/pending': typeof DialogPendingRoute
  '/dialog/personal_sign': typeof DialogPersonal_signRoute
  '/dialog/playground': typeof DialogPlaygroundRoute
  '/dialog/success': typeof DialogSuccessRoute
  '/dialog/wallet_addFunds': typeof DialogWallet_addFundsRoute
  '/dialog/wallet_connect': typeof DialogWallet_connectRoute
  '/dialog/wallet_grantAdmin': typeof DialogWallet_grantAdminRoute
  '/dialog/wallet_grantPermissions': typeof DialogWallet_grantPermissionsRoute
  '/dialog/wallet_prepareUpgradeAccount': typeof DialogWallet_prepareUpgradeAccountRoute
  '/dialog/wallet_revokeAdmin': typeof DialogWallet_revokeAdminRoute
  '/dialog/wallet_revokePermissions': typeof DialogWallet_revokePermissionsRoute
  '/dialog/wallet_sendCalls': typeof DialogWallet_sendCallsRoute
  '/dialog': typeof DialogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dialog/$': typeof DialogSplatRoute
  '/dialog/account_verifyEmail': typeof DialogAccount_verifyEmailRoute
  '/dialog/eth_requestAccounts': typeof DialogEth_requestAccountsRoute
  '/dialog/eth_sendTransaction': typeof DialogEth_sendTransactionRoute
  '/dialog/eth_signTypedData_v4': typeof DialogEth_signTypedData_v4Route
  '/dialog/pending': typeof DialogPendingRoute
  '/dialog/personal_sign': typeof DialogPersonal_signRoute
  '/dialog/playground': typeof DialogPlaygroundRoute
  '/dialog/success': typeof DialogSuccessRoute
  '/dialog/wallet_addFunds': typeof DialogWallet_addFundsRoute
  '/dialog/wallet_connect': typeof DialogWallet_connectRoute
  '/dialog/wallet_grantAdmin': typeof DialogWallet_grantAdminRoute
  '/dialog/wallet_grantPermissions': typeof DialogWallet_grantPermissionsRoute
  '/dialog/wallet_prepareUpgradeAccount': typeof DialogWallet_prepareUpgradeAccountRoute
  '/dialog/wallet_revokeAdmin': typeof DialogWallet_revokeAdminRoute
  '/dialog/wallet_revokePermissions': typeof DialogWallet_revokePermissionsRoute
  '/dialog/wallet_sendCalls': typeof DialogWallet_sendCallsRoute
  '/dialog/': typeof DialogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dialog/$'
    | '/dialog/account_verifyEmail'
    | '/dialog/eth_requestAccounts'
    | '/dialog/eth_sendTransaction'
    | '/dialog/eth_signTypedData_v4'
    | '/dialog/pending'
    | '/dialog/personal_sign'
    | '/dialog/playground'
    | '/dialog/success'
    | '/dialog/wallet_addFunds'
    | '/dialog/wallet_connect'
    | '/dialog/wallet_grantAdmin'
    | '/dialog/wallet_grantPermissions'
    | '/dialog/wallet_prepareUpgradeAccount'
    | '/dialog/wallet_revokeAdmin'
    | '/dialog/wallet_revokePermissions'
    | '/dialog/wallet_sendCalls'
    | '/dialog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dialog/$'
    | '/dialog/account_verifyEmail'
    | '/dialog/eth_requestAccounts'
    | '/dialog/eth_sendTransaction'
    | '/dialog/eth_signTypedData_v4'
    | '/dialog/pending'
    | '/dialog/personal_sign'
    | '/dialog/playground'
    | '/dialog/success'
    | '/dialog/wallet_addFunds'
    | '/dialog/wallet_connect'
    | '/dialog/wallet_grantAdmin'
    | '/dialog/wallet_grantPermissions'
    | '/dialog/wallet_prepareUpgradeAccount'
    | '/dialog/wallet_revokeAdmin'
    | '/dialog/wallet_revokePermissions'
    | '/dialog/wallet_sendCalls'
    | '/dialog'
  id:
    | '__root__'
    | '/'
    | '/dialog/$'
    | '/dialog/account_verifyEmail'
    | '/dialog/eth_requestAccounts'
    | '/dialog/eth_sendTransaction'
    | '/dialog/eth_signTypedData_v4'
    | '/dialog/pending'
    | '/dialog/personal_sign'
    | '/dialog/playground'
    | '/dialog/success'
    | '/dialog/wallet_addFunds'
    | '/dialog/wallet_connect'
    | '/dialog/wallet_grantAdmin'
    | '/dialog/wallet_grantPermissions'
    | '/dialog/wallet_prepareUpgradeAccount'
    | '/dialog/wallet_revokeAdmin'
    | '/dialog/wallet_revokePermissions'
    | '/dialog/wallet_sendCalls'
    | '/dialog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DialogSplatRoute: typeof DialogSplatRoute
  DialogAccount_verifyEmailRoute: typeof DialogAccount_verifyEmailRoute
  DialogEth_requestAccountsRoute: typeof DialogEth_requestAccountsRoute
  DialogEth_sendTransactionRoute: typeof DialogEth_sendTransactionRoute
  DialogEth_signTypedData_v4Route: typeof DialogEth_signTypedData_v4Route
  DialogPendingRoute: typeof DialogPendingRoute
  DialogPersonal_signRoute: typeof DialogPersonal_signRoute
  DialogPlaygroundRoute: typeof DialogPlaygroundRoute
  DialogSuccessRoute: typeof DialogSuccessRoute
  DialogWallet_addFundsRoute: typeof DialogWallet_addFundsRoute
  DialogWallet_connectRoute: typeof DialogWallet_connectRoute
  DialogWallet_grantAdminRoute: typeof DialogWallet_grantAdminRoute
  DialogWallet_grantPermissionsRoute: typeof DialogWallet_grantPermissionsRoute
  DialogWallet_prepareUpgradeAccountRoute: typeof DialogWallet_prepareUpgradeAccountRoute
  DialogWallet_revokeAdminRoute: typeof DialogWallet_revokeAdminRoute
  DialogWallet_revokePermissionsRoute: typeof DialogWallet_revokePermissionsRoute
  DialogWallet_sendCallsRoute: typeof DialogWallet_sendCallsRoute
  DialogIndexRoute: typeof DialogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/': {
      id: '/dialog/'
      path: '/dialog'
      fullPath: '/dialog/'
      preLoaderRoute: typeof DialogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_sendCalls': {
      id: '/dialog/wallet_sendCalls'
      path: '/dialog/wallet_sendCalls'
      fullPath: '/dialog/wallet_sendCalls'
      preLoaderRoute: typeof DialogWallet_sendCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_revokePermissions': {
      id: '/dialog/wallet_revokePermissions'
      path: '/dialog/wallet_revokePermissions'
      fullPath: '/dialog/wallet_revokePermissions'
      preLoaderRoute: typeof DialogWallet_revokePermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_revokeAdmin': {
      id: '/dialog/wallet_revokeAdmin'
      path: '/dialog/wallet_revokeAdmin'
      fullPath: '/dialog/wallet_revokeAdmin'
      preLoaderRoute: typeof DialogWallet_revokeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_prepareUpgradeAccount': {
      id: '/dialog/wallet_prepareUpgradeAccount'
      path: '/dialog/wallet_prepareUpgradeAccount'
      fullPath: '/dialog/wallet_prepareUpgradeAccount'
      preLoaderRoute: typeof DialogWallet_prepareUpgradeAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_grantPermissions': {
      id: '/dialog/wallet_grantPermissions'
      path: '/dialog/wallet_grantPermissions'
      fullPath: '/dialog/wallet_grantPermissions'
      preLoaderRoute: typeof DialogWallet_grantPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_grantAdmin': {
      id: '/dialog/wallet_grantAdmin'
      path: '/dialog/wallet_grantAdmin'
      fullPath: '/dialog/wallet_grantAdmin'
      preLoaderRoute: typeof DialogWallet_grantAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_connect': {
      id: '/dialog/wallet_connect'
      path: '/dialog/wallet_connect'
      fullPath: '/dialog/wallet_connect'
      preLoaderRoute: typeof DialogWallet_connectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/wallet_addFunds': {
      id: '/dialog/wallet_addFunds'
      path: '/dialog/wallet_addFunds'
      fullPath: '/dialog/wallet_addFunds'
      preLoaderRoute: typeof DialogWallet_addFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/success': {
      id: '/dialog/success'
      path: '/dialog/success'
      fullPath: '/dialog/success'
      preLoaderRoute: typeof DialogSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/playground': {
      id: '/dialog/playground'
      path: '/dialog/playground'
      fullPath: '/dialog/playground'
      preLoaderRoute: typeof DialogPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/personal_sign': {
      id: '/dialog/personal_sign'
      path: '/dialog/personal_sign'
      fullPath: '/dialog/personal_sign'
      preLoaderRoute: typeof DialogPersonal_signRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/pending': {
      id: '/dialog/pending'
      path: '/dialog/pending'
      fullPath: '/dialog/pending'
      preLoaderRoute: typeof DialogPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/eth_signTypedData_v4': {
      id: '/dialog/eth_signTypedData_v4'
      path: '/dialog/eth_signTypedData_v4'
      fullPath: '/dialog/eth_signTypedData_v4'
      preLoaderRoute: typeof DialogEth_signTypedData_v4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/eth_sendTransaction': {
      id: '/dialog/eth_sendTransaction'
      path: '/dialog/eth_sendTransaction'
      fullPath: '/dialog/eth_sendTransaction'
      preLoaderRoute: typeof DialogEth_sendTransactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/eth_requestAccounts': {
      id: '/dialog/eth_requestAccounts'
      path: '/dialog/eth_requestAccounts'
      fullPath: '/dialog/eth_requestAccounts'
      preLoaderRoute: typeof DialogEth_requestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/account_verifyEmail': {
      id: '/dialog/account_verifyEmail'
      path: '/dialog/account_verifyEmail'
      fullPath: '/dialog/account_verifyEmail'
      preLoaderRoute: typeof DialogAccount_verifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialog/$': {
      id: '/dialog/$'
      path: '/dialog/$'
      fullPath: '/dialog/$'
      preLoaderRoute: typeof DialogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DialogSplatRoute: DialogSplatRoute,
  DialogAccount_verifyEmailRoute: DialogAccount_verifyEmailRoute,
  DialogEth_requestAccountsRoute: DialogEth_requestAccountsRoute,
  DialogEth_sendTransactionRoute: DialogEth_sendTransactionRoute,
  DialogEth_signTypedData_v4Route: DialogEth_signTypedData_v4Route,
  DialogPendingRoute: DialogPendingRoute,
  DialogPersonal_signRoute: DialogPersonal_signRoute,
  DialogPlaygroundRoute: DialogPlaygroundRoute,
  DialogSuccessRoute: DialogSuccessRoute,
  DialogWallet_addFundsRoute: DialogWallet_addFundsRoute,
  DialogWallet_connectRoute: DialogWallet_connectRoute,
  DialogWallet_grantAdminRoute: DialogWallet_grantAdminRoute,
  DialogWallet_grantPermissionsRoute: DialogWallet_grantPermissionsRoute,
  DialogWallet_prepareUpgradeAccountRoute:
    DialogWallet_prepareUpgradeAccountRoute,
  DialogWallet_revokeAdminRoute: DialogWallet_revokeAdminRoute,
  DialogWallet_revokePermissionsRoute: DialogWallet_revokePermissionsRoute,
  DialogWallet_sendCallsRoute: DialogWallet_sendCallsRoute,
  DialogIndexRoute: DialogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
