/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 48a0b5401b67a79eebaa402adec9538b)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    NONCE_STORE: KVNamespace
    JWT_SECRET: string
    VITE_SIWE_URL: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'JWT_SECRET' | 'VITE_SIWE_URL'>
    > {}
}
