/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 50ae63f3665d6c1ecfae97acb2bbbab3)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    PORT: string
    ENVIRONMENT: string
    LOGGING: string
    JWT_SECRET: string
    PRIVY_APP_ID: string
    PRIVY_JWKS_ENDPOINT: string
    PRIVY_APP_SECRET: string
    VITE_PRIVY_APP_ID: string
    MERCHANT_ADDRESS: string
    MERCHANT_PRIVATE_KEY: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'PORT'
        | 'ENVIRONMENT'
        | 'LOGGING'
        | 'JWT_SECRET'
        | 'PRIVY_APP_ID'
        | 'PRIVY_JWKS_ENDPOINT'
        | 'PRIVY_APP_SECRET'
        | 'VITE_PRIVY_APP_ID'
        | 'MERCHANT_ADDRESS'
        | 'MERCHANT_PRIVATE_KEY'
      >
    > {}
}
