/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout.transactions'
import { Route as LayoutSessionsRouteImport } from './routes/_layout.sessions'
import { Route as LayoutRecoveryV1RouteImport } from './routes/_layout.recovery-v1'
import { Route as LayoutRecoveryRouteImport } from './routes/_layout.recovery'
import { Route as LayoutPortfolioRouteImport } from './routes/_layout.portfolio'
import { Route as LayoutAssetsRouteImport } from './routes/_layout.assets'
import { Route as LayoutAboutRouteImport } from './routes/_layout.about'
import { Route as LayoutEmailVerifyRouteImport } from './routes/_layout.email.verify'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecoveryV1Route = LayoutRecoveryV1RouteImport.update({
  id: '/recovery-v1',
  path: '/recovery-v1',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecoveryRoute = LayoutRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfolioRoute = LayoutPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAssetsRoute = LayoutAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailVerifyRoute = LayoutEmailVerifyRouteImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/playground': typeof PlaygroundRoute
  '/about': typeof LayoutAboutRoute
  '/assets': typeof LayoutAssetsRoute
  '/portfolio': typeof LayoutPortfolioRoute
  '/recovery': typeof LayoutRecoveryRoute
  '/recovery-v1': typeof LayoutRecoveryV1Route
  '/sessions': typeof LayoutSessionsRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/email/verify': typeof LayoutEmailVerifyRoute
}
export interface FileRoutesByTo {
  '/playground': typeof PlaygroundRoute
  '/about': typeof LayoutAboutRoute
  '/assets': typeof LayoutAssetsRoute
  '/portfolio': typeof LayoutPortfolioRoute
  '/recovery': typeof LayoutRecoveryRoute
  '/recovery-v1': typeof LayoutRecoveryV1Route
  '/sessions': typeof LayoutSessionsRoute
  '/transactions': typeof LayoutTransactionsRoute
  '/': typeof LayoutIndexRoute
  '/email/verify': typeof LayoutEmailVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/assets': typeof LayoutAssetsRoute
  '/_layout/portfolio': typeof LayoutPortfolioRoute
  '/_layout/recovery': typeof LayoutRecoveryRoute
  '/_layout/recovery-v1': typeof LayoutRecoveryV1Route
  '/_layout/sessions': typeof LayoutSessionsRoute
  '/_layout/transactions': typeof LayoutTransactionsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/email/verify': typeof LayoutEmailVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/playground'
    | '/about'
    | '/assets'
    | '/portfolio'
    | '/recovery'
    | '/recovery-v1'
    | '/sessions'
    | '/transactions'
    | '/email/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/playground'
    | '/about'
    | '/assets'
    | '/portfolio'
    | '/recovery'
    | '/recovery-v1'
    | '/sessions'
    | '/transactions'
    | '/'
    | '/email/verify'
  id:
    | '__root__'
    | '/_layout'
    | '/playground'
    | '/_layout/about'
    | '/_layout/assets'
    | '/_layout/portfolio'
    | '/_layout/recovery'
    | '/_layout/recovery-v1'
    | '/_layout/sessions'
    | '/_layout/transactions'
    | '/_layout/'
    | '/_layout/email/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recovery-v1': {
      id: '/_layout/recovery-v1'
      path: '/recovery-v1'
      fullPath: '/recovery-v1'
      preLoaderRoute: typeof LayoutRecoveryV1RouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recovery': {
      id: '/_layout/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof LayoutRecoveryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolio': {
      id: '/_layout/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof LayoutPortfolioRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/assets': {
      id: '/_layout/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof LayoutAssetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email/verify': {
      id: '/_layout/email/verify'
      path: '/email/verify'
      fullPath: '/email/verify'
      preLoaderRoute: typeof LayoutEmailVerifyRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutAssetsRoute: typeof LayoutAssetsRoute
  LayoutPortfolioRoute: typeof LayoutPortfolioRoute
  LayoutRecoveryRoute: typeof LayoutRecoveryRoute
  LayoutRecoveryV1Route: typeof LayoutRecoveryV1Route
  LayoutSessionsRoute: typeof LayoutSessionsRoute
  LayoutTransactionsRoute: typeof LayoutTransactionsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEmailVerifyRoute: typeof LayoutEmailVerifyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutAssetsRoute: LayoutAssetsRoute,
  LayoutPortfolioRoute: LayoutPortfolioRoute,
  LayoutRecoveryRoute: LayoutRecoveryRoute,
  LayoutRecoveryV1Route: LayoutRecoveryV1Route,
  LayoutSessionsRoute: LayoutSessionsRoute,
  LayoutTransactionsRoute: LayoutTransactionsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEmailVerifyRoute: LayoutEmailVerifyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
